spring.application.name=tripmate
server.port:8080
spring.datasource.url=jdbc:mysql://localhost:3306/trip_mate_db
#spring.datasource.url=jdbc:mysql://mysql:3306/trip_mate_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Nivel por defecto para toda la app
logging.level.root=INFO

# Logs detallados para el controller
logging.level.com.tripmate.tripmate.api.trip=DEBUG

# Logs detallados para la capa repository/service
logging.level.com.tripmate.tripmate.infrastructure.repository.trip=DEBUG

# Kafka broker local
spring.kafka.bootstrap-servers: localhost:9092

# Serializadores (para String key y String value)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

topic.name=notification-topic

#JsonOpenAPi y Swagger-UI http://localhost:8080/v3/api-docs , http://localhost:8080/webjars/swagger-ui/index.html
