spring.application.name=tripmate
server.port:8082
spring.datasource.url=jdbc:mysql://localhost:3306/trip_mate_db
#spring.datasource.url=jdbc:mysql://mysql:3306/trip_mate_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka broker local
spring.kafka.bootstrap-servers: localhost:9092

# Serializadores (para String key y String value)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

topic.name=notification-topic